### PR TITLE
SLING-10010 update to sling-bundle-parent 43

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by joerghoh** [comment]
@kwin I think we should drop the dependency to sling-commons-testing, we should start to use the sling mocks instead (they are maintained and much more easier to use). For that reason I added the 2 relevant classes in here, which serve as a replacement for the ones of sling-commons-testing, but Oak-based.

I also think that we should invest in some time and update some Junit3 tests to Junit4, which I haven't done yet to keep the scope of the patch as narrow as possible.

**Comment by kwin** [comment]
I would like to separate these things. The update to a newer parent is not directly related to migrating to other testing classes. This PR is now 7 month old (at that time parent 40 was the latest) and there was never any review. Feel free to pick it up from where it is and update to parent 43. I can do a review afterwards.

**Comment by joerghoh** [comment]
ok, then I will just update it to parent 43 and leave everything else for a different ticket.

**Comment by joerghoh** [comment]
@kwin, @cziegeler : Can you please review?

**Comment by kwin** [comment]
@joerghoh Please remove https://github.com/apache/sling-org-apache-sling-jcr-resource/pull/12/commits/6c9ec7ecf1851a4447d7ebc6695e9fda71cc8e19 from this PR as agreed in https://github.com/apache/sling-org-apache-sling-jcr-resource/pull/12#issuecomment-881949498

**Comment by joerghoh** [comment]
@kwin sorry, then there was a mis-understanding.

I raised #14 just to update the unittests, will remove the commit from here.

**Comment by joerghoh** [comment]
Now we have here just the necessary POM updates.

**Comment by joerghoh** [comment]
@cziegeler can you please review?

**Comment by cziegeler** [comment]
Looks ok to me, the best is to simply compare the resulting bundles - if the manifest and contents are the same, then the change should be good

**Comment by joerghoh** [comment]
[osgi-ds-metatype-diff ](https://github.com/jsedding/osgi-ds-metatype-diff) does not show any difference between 3.0.22 and this branch.

**Pull request merged**
