### PR TITLE
Use javax.jcr.Item.getParent() when resolving parent JCR node in JcrResourceProvider#getParent

### PR DESCRIPTION
**Pull request by smiroslav**
https://issues.apache.org/jira/browse/SLING-10011

### CODE REVIEW

**Comment by cziegeler** [comment]
I don't want to cause pain here but now we have the opposite problem :) if a RepositoryException somewhere occurs for whatever reason then it was logged as a warn - now its not logged at all anymore

**Comment by jsedding** [comment]
@cziegeler I assume we would get the old behaviour (or very close) if we catch `ItemNotFoundException` and `AccessDeniedException` where no warning is logged. In case a straight `RepositoryException` is thrown, a warning should be logged. WDYT?

From the javadoc of `Item.getParent()`:
> @throws ItemNotFoundException if this <code>Item</code> is the root node of a workspace.
> @throws AccessDeniedException if the current session does not have sufficent access to retrieve the parent of this item.
> @throws RepositoryException   if another error occurs.

PS: I'd still prefer a performance fix for `getItemOrNull()` in Oak, because that would be generally useful. But I understand it is a lot more work.

**Comment by cziegeler** [comment]
yes, I think catching those two exceptions and not logging for them should do the trick.

**Comment by cziegeler** [comment]
Thanks, I think we should now have the same behaviour

**Comment by anchela** [comment]
closing this PR as it has been solved by using the new method JackrabbitSession.getParentOrNull

**Pull request closed without merging**
