### PR TITLE
SLING-11066 sort URIProvider implementations by ranking (descending)

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by cziegeler** [comment]
I think the code can completely replaced by using a field reference where DS sorts the services by service ranking

**Comment by kwin** [comment]
How and when to update then the `uriProviderReference` in the `JcrProviderStateFactory`?

**Comment by cziegeler** [comment]
There are different ways to do this - a concurrent collection could be used as the base, which then does not require to update the reference anymore, event methods with a custom collection could be implemented etc.
The osgi commons approach is outdated. If you want to stick to the bind/unbind methods you can get the ServiceReference as one argument and easily sort based on that one (it is comparable) - avoid the extra dependency

**Comment by kwin** [comment]
> a concurrent collection could be used as the base

IMHO I need to use the option "Replace Field" as otherwise the order is not ensured (http://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-reference.field.option)

> event methods with a custom collection could be implemented

I don't think a custom collection can be used for Field injection with the replace field option or am I missing something here.

> you can get the ServiceReference as one argument and easily sort based on that one (it is comparable)

This would require a similar implementation as in `RankedServices`. Would you be fine with embedded that class (to prevent the extra dependency)?

**Comment by cziegeler** [comment]
I don't think you need RankedServices - you can keep the concurrent map, on bind/unbind create a List from the values and call Collections.sort() on that list. So you just need one additional line.

**Comment by kwin** [comment]
bq. call Collections.sort() on that list

The map only contains `UriProvider` (both as keys and values). Based on that you cannot do a proper sorting. That would require persisting the ServiceReference along with it.

**Comment by kwin** [comment]
In https://github.com/apache/sling-org-apache-sling-jcr-resource/pull/20/commits/ea522188c7027ab22cb18f3c02d781211ab4ebaa I choose an approach similar to how Felix SCR is doing it in https://github.com/apache/felix-dev/blob/983ebd960c5181d8860f3219f9cd0cd9c49b9c3d/scr/src/main/java/org/apache/felix/scr/impl/manager/ComponentContextImpl.java#L337. @cziegeler Please have another look. I couldn't come up with anything simpler than that.

**Review by cziegeler — APPROVED** [review]
Lgtm, thanks

**Pull request merged**
